name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    tags:
      - v1.*.*
      
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: TEST
    if: github.ref == 'refs/tags/v1.5.6'
    steps:
      - run: |
          echo '${{ toJSON(github.ref) }}'
          echo '${{ toJSON(github.env) }}'
          echo '${{secrets.ABC1}}'
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: "14"
      # - run: npm install -g bats
      # - run: bats -v
